name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.1.0
      with:
        run_install: false

    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version-file: ./.nvmrc
        cache: pnpm

    - name: Install
      run: pnpm install
      shell: bash
